"""
Created on Fri Jul 21 11:18:40 2023.

@author: js2746
"""

import pytest
import numpy as np
from nougat import *
from pathlib import Path
from collections import namedtuple


Comparison = namedtuple("Comparison", "test_data ref_data")


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%% FIXTURES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

@pytest.fixture
def cwd():
    """
    Get current working directory.

    """
    return Path.cwd()


@pytest.fixture(scope='function', params=["cart", "polar"])
def coordsys(request):
    """
    Supply the proper coordinate system name to the test function requesting it.

    """
    return request.param


@pytest.fixture(scope='function', params=["zone", "ztwo", "zplus", "zzero"])
def surface4(request):
    """
    Supply all four surfaces to the test function requesting it.

    """
    return request.param


@pytest.fixture(scope='function', params=["zone", "ztwo"])
def surface2(request):
    """
    Supply z1 and z2 to the test function requesting it.

    """
    return request.param


@pytest.fixture(scope='function', params=["E-protein", "flat"])
def system(request):
    """
    Supply the system being tested to the test function requesting it.

    """
    return request.param


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%% FUNCTIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

def make_root_path(wd, coords, sys, test=True):
    """
    Make the correct path for nougat testing to use. Should point to the \
    outputs folder generated by nougat.tcl.

    Parameters
    ----------
    wd : Path
        The current working directory.
    coords : str
        The coordinate system used.
    sys : str
        The name of the system.
    test : bool
        If True, generate path to test directory. If False, generate path to \
        reference values directory.

    Returns
    -------
    Path.

    """
    if sys == "E-protein":
        directory = "E-protein_trajectory"
    elif sys == "flat":
        directory = "flat_surface_test"
    if test:
        subdir = "test_"
    else:
        subdir = directory + "_"
    if coords == "cart":
        root = wd.joinpath(directory, subdir + "cart_5_5_0_-1_1")
    elif coords == "polar":
        root = wd.joinpath(directory, subdir + "polar_3_12_0_-1_1")
    return root


def make_py_paths(wd, system, coord, surf, quant, file_format):
    """
    Concatenate strings together to make the path to the correct test files.

    Parameters
    ----------
    wd: string
        Path to current working directory.
    system: string
        Which test system the test pertains to.
    coord: string
        Coordinate system; 'cart' or 'polar'
    surf: sring
        The membrane surface in question (z1, z2, z0, or z+)
    quant: string
        The quantity being measured(height, thickness, curvature, etc.)
    file_format: string
        "dat" or "npy"

    Returns
    -------
    expected: Path
        Path to the stored reference values.

    """
    if file_format == "npy":
        file_type = "trajectory"
    elif file_format == "dat":
        file_type = "average"
    if coord == "cart":
        coordsys_path = "_cart_5_5_0_-1_1"
    elif coord == "polar":
        coordsys_path = "_polar_3_12_0_-1_1"
    if system == "E-protein":
        directory = "E-protein_trajectory"
    elif system == "flat":
        directory = "flat_surface_test"
    expected = wd.joinpath(directory, system + coordsys_path, file_type, quant, surf + "." + file_format)
    return expected


def make_tcl_paths(wd, coords, sys, surf):
    """
    Concatenate strings together to make the paths to the correct and reference\
    files.

    Parameters
    ----------
    wd : Path
        The current working directory.
    coords : str
        The coordinate system used.
    sys : str
        The name of the system.
    surf: sring
        The membrane surface in question (z1, z2, z0, or z+)

    Returns
    -------
    (Path, Path)

    """
    ref_root = make_root_path(wd, coords, sys, test=False)
    ref_path = ref_root.joinpath("tcl_output", "height", surf + ".dat")

    test_root = make_root_path(wd, coords, sys, test=True)
    test_path = test_root.joinpath("tcl_output", "height", surf + ".dat")
    return (ref_path.resolve(), test_path.resolve())


def arrays_equal(paths, filetype, tolerance):
    """
    Determine whether two arrays have identical elements.

    Parameters
    ----------
    paths: Comparison named tuple
        Named tuple of two path objects.
    filetype: string
        The filetype of f1 and f2
    tolerance: float
        The amount of tolerance you have for differences between files. Should \
            be a small number!

    Returns
    -------
    Bool
        Whether or not the two arrays contain identical elements.

    """
    if filetype == "npy":
        f1 = np.load(paths[0])
        f2 = np.load(paths[1])
    elif filetype == "dat":
        f1 = np.genfromtxt(paths[0], missing_values="nan", filling_values=np.nan)
        f2 = np.genfromtxt(paths[1], missing_values="nan", filling_values=np.nan)

    if tolerance == 0:
        return np.array_equal(f1, f2, equal_nan=True)
    elif tolerance > 0:
        return np.allclose(f1, f2, rtol=0, atol=tolerance, equal_nan=True)
    else:
        raise ValueError("Tolerance must be positive or 0.")


# %%%%%%%%%%%%%%%%%%%%%%%%%% TESTS ARE BELOW %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# Test if TCL outputs match

def test_if_tcl_heights_match(cwd, coordsys, system, surface4):
    if surface4 == "zplus":
        pytest.skip("nougat.tcl does not measure zplus; skipping zplus test")
    else:
        paths = make_tcl_paths(cwd, coordsys, system, surface4)
        assert arrays_equal(paths, 'dat', 1e-11)

# Still needed: density, order, tilt tests


# Test if python trajectory outputs match

def test_if_heights_match(cwd, coordsys, surface4, system):
    testing_path = make_testing_path(cwd, coordsys, system)
    ref_path = make_py_paths(cwd, system, coordsys, surface4, "height", "npy")
    
    if coordsys == "cart":
        polar = False
    elif coordsys == "polar":
        polar = True
    m = run_nougat(testing_path, polar, "h")
    if surface4 in ["zone", "ztwo", "zzero"]:
        test_array = flatten_obj(getattr(m, surface4).traj)
    elif surface4 == "zplus":
        test_array = flatten_obj(m.height.plus.traj)
    assert arrays_equal((ref_path, test_array), 'npy', 1e-11)


def test_if_thicknesses_match(cwd, coordsys, surface2, system):
    ref_path = make_py_paths(cwd, system, coordsys, surface2, "thickness", "npy")
    testing_path = make_testing_path(cwd, coordsys, system)
    if coordsys == "cart":
        polar = False
    elif coordsys == "polar":
        polar = True
    m = run_nougat(testing_path, polar, "t")

    assert arrays_equal((ref_path, test_array), 'npy', 1e-11)


"""
def test_whether_flat(cwd, coordsys):
    if coordsys == "cart":
        settings = "_5_5_0_-1_1"
    else:
        settings = "_3_12_0_-1_1"
    Hone = np.load(cwd.joinpath("flat_surface_test", "test_" + coordsys + settings, "trajectory", "curvature", "mean", "zone.npy"))
    Htwo = np.load(cwd.joinpath("flat_surface_test", "test_" + coordsys + settings, "trajectory", "curvature", "mean", "ztwo.npy"))
    Hplus = Hone + Htwo / 2.0
    avgHplus = np.nanmean(Hplus)
    assert avgHplus <= 0.000000000001 and avgHplus >= -0.000000000001


def test_whether_flat_gaussian(cwd, coordsys):
    if coordsys == "cart":
        settings = "_5_5_0_-1_1"
    else:
        settings = "_3_12_0_-1_1"
    Kone = np.load(cwd.joinpath("flat_surface_test", "test_" + coordsys + settings, "trajectory", "curvature", "gaussian", "zone.npy"))
    Ktwo = np.load(cwd.joinpath("flat_surface_test", "test_" + coordsys + settings, "trajectory", "curvature", "gaussian", "ztwo.npy"))
    Kplus = Kone + Ktwo / 2.0
    avgKplus = np.nanmean(Kplus)
    assert avgKplus <= 0.000000000001 and avgKplus >= -0.000000000001
"""


@pytest.mark.xfail(strict=True)
def test_if_leaflets_heights_are_distinct(cwd, coordsys, system):
    zone_test = make_py_paths(cwd, system, coordsys, "zone", "height", "npy")
    ztwo_test = make_py_paths(cwd, system, coordsys, "ztwo", "height", "npy")
    assert arrays_equal((zone_test, ztwo_test), 'npy', 0)


@pytest.mark.xfail(strict=True)
def test_if_leaflet_thicknesses_are_distinct(cwd, coordsys, system):
    zone_test = make_py_paths(cwd, system, coordsys, "zone", "thickness", "npy")
    ztwo_test = make_py_paths(cwd, system, coordsys, "ztwo", "thickness", "npy")
    assert arrays_equal((zone_test, ztwo_test), 'npy', 0)

# Still needed: curvature, order, tilt


# Test if python time-averages match

def test_if_avg_heights_match(cwd, coordsys, surface4, system):
    path = make_py_paths(cwd, system, coordsys, surface4, "height", "dat")
    assert arrays_equal(path, 'dat', 1e-11)


# Still needed: curvature, thickness, order, tilt, normal_vectors


# BELOW: old density tests that need to be re-implemented
"""
def test_if_densities_match(cwd, coordsys, surface2):
    if coordsys == "cart":
        coordsys_path = "_cart_5_5_0_-1_1"
    elif coordsys == "polar":
        coordsys_path = "_polar_3_12_0_-1_1"
    exp = cwd.joinpath("E-protein_trajectory/E-protein" + coordsys_path, "trajectory", "density", "DTPC", surface2 + ".npy")
    test = cwd.joinpath("E-protein_trajectory/test" + coordsys_path, "trajectory", "density", "DTPC", surface2 + ".npy")
    paths = Comparison(test, exp)
    assert arrays_equal(paths, 'npy', 1e-11)


def test_if_avg_densities_match(cwd, coordsys, surface2, system):
    paths = make_avg_paths(cwd, system, coordsys, surface2, "avgdensity")
    assert arrays_equal(paths, 'dat', 1e-11)
"""
